language: ruby
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - ruby-head
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
before_script:
  - cp spec/dummy/config/database.travis.yml spec/dummy/config/database.yml
  - psql -c 'create database image_authentication_test' -U postgres
